export const light = {
  primary: "#4BA151",
  secondary: "#BB582A",
  bgPrimary: "#fff",
  bgPrimaryAlpha: "#ffffff75",
  bgSecondary: "#ddd",
  bgSecondaryAlpha: "#dddddd75",
  bgTertiary: "#eeeeee85",
  borderPrimary: "#252525",
  borderSecondary: "#b3b3b3",
  txtPrimary: "#3B3B3B",
  txtSecondary: "#b3b3b3",
  error: "#c0392b",
  warning: "#f1c40f",
  success: "#2ecc71",
  white: "#fff",
  black: "#252525",
  blackAlpha: "#25252575",
};

export const dark = {
  primary: light.primary,
  secondary: light.secondary,
  bgPrimary: "#3B3B3B",
  bgPrimaryAlpha: "#3B3B3B75",
  bgSecondary: "#252525",
  bgSecondaryAlpha: "#25252575",
  bgTertiary: "#41414185",
  borderPrimary: light.borderSecondary,
  borderSecondary: light.borderPrimary,
  txtPrimary: light.txtSecondary,
  txtSecondary: light.txtPrimary,
  error: light.error,
  warning: light.warning,
  success: light.success,
  white: light.white,
  black: light.black,
  blackAlpha: light.blackAlpha,
};
